default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: every_leaf_exam_development
test:
  <<: *default
  database: every_leaf_exam_test

production:
  <<: *default
  database: every_leaf_exam_production
  username: every_leaf_exam
  password: <%= ENV['EVERY_LEAF_EXAM_DATABASE_PASSWORD'] %>
